In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [13]:
# Replace the path with the correct path for your data.
y2015 = pd.read_csv('LoanStats3dd.csv', skipinitialspace=True, header=1, nrows=50000, low_memory=False)

# Convert ID and Interest Rate to numeric.
y2015['id'] = pd.to_numeric(y2015['id'], errors='coerce')
y2015['int_rate'] = pd.to_numeric(y2015['int_rate'].str.strip('%'), errors='coerce')

# Drop other columns with many unique variables
y2015.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'addr_state', 'desc'], 1, inplace=True)

In [14]:
y2015.fillna(0, inplace=True)
# Remove two summary rows at the end that don't actually contain data.
y2015 = y2015[:-2]
y2015.describe()

id  member_id     loan_amnt   funded_amnt  funded_amnt_inv  \
count  49998.0    49998.0  49998.000000  49998.000000     49998.000000   
mean       0.0        0.0  15020.930837  15020.930837     15013.398036   
std        0.0        0.0   8676.010835   8676.010835      8671.041261   
min        0.0        0.0   1000.000000   1000.000000       950.000000   
25%        0.0        0.0   8000.000000   8000.000000      8000.000000   
50%        0.0        0.0  14000.000000  14000.000000     13900.000000   
75%        0.0        0.0  20000.000000  20000.000000     20000.000000   
max        0.0        0.0  35000.000000  35000.000000     35000.000000   

           int_rate   installment    annual_inc           dti   delinq_2yrs  \
count  49998.000000  49998.000000  4.999800e+04  49998.000000  49998.000000   
mean      12.234707    434.133187  7.920346e+04     19.337612      0.345714   
std        4.190681    247.501541  1.013235e+05      9.811819      0.910273   
min        5.320000     14.770000  0.000000e+00      0.000000      0.000000   
25%        9.170000    255.040000  4.800000e+04     12.672500      0.000000   
50%       11.990000    378.150000  6.600000e+04     18.820000      0.000000   
75%       14.480000    573.640000  9.500000e+04     25.617500      0.000000   
max       28.990000   1354.660000  9.000000e+06    999.000000     15.000000   

            ...         deferral_term  hardship_amount  hardship_length  \
count       ...          49998.000000     49998.000000     49998.000000   
mean        ...              0.024001         1.038370         0.024001   
std         ...              0.267261        15.026398         0.267261   
min         ...              0.000000         0.000000         0.000000   
25%         ...              0.000000         0.000000         0.000000   
50%         ...              0.000000         0.000000         0.000000   
75%         ...              0.000000         0.000000         0.000000   
max         ...              3.000000       629.700000         3.000000   

       hardship_dpd  orig_projected_additional_accrued_interest  \
count  49998.000000                                49998.000000   
mean       0.111344                                    2.470400   
std        1.528674                                   40.098972   
min        0.000000                                    0.000000   
25%        0.000000                                    0.000000   
50%        0.000000                                    0.000000   
75%        0.000000                                    0.000000   
max       30.000000                                 1889.100000   

       hardship_payoff_balance_amount  hardship_last_payment_amount  \
count                    49998.000000                  49998.000000   
mean                        83.406663                      1.523049   
std                       1099.035267                     23.843706   
min                          0.000000                      0.000000   
25%                          0.000000                      0.000000   
50%                          0.000000                      0.000000   
75%                          0.000000                      0.000000   
max                      29401.040000                    926.410000   

       settlement_amount  settlement_percentage  settlement_term  
count       49998.000000           49998.000000     49998.000000  
mean          150.937083               1.411675         0.410516  
std          1057.100180               8.081584         2.670493  
min             0.000000               0.000000         0.000000  
25%             0.000000               0.000000         0.000000  
50%             0.000000               0.000000         0.000000  
75%             0.000000               0.000000         0.000000  
max         22000.000000              75.000000        65.000000  

[8 rows x 108 columns]

In [15]:
categorical = y2015.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

term
2
grade
7
emp_length
12
home_ownership
4
verification_status
3
issue_d
2
loan_status
7
pymnt_plan
2
purpose
12
title
13
initial_list_status
2
last_pymnt_d
40
next_pymnt_d
3
last_credit_pull_d
41
application_type
2
verification_status_joint
2
hardship_flag
2
hardship_type
2
hardship_reason
10
hardship_status
4
hardship_start_date
25
hardship_end_date
25
payment_plan_start_date
25
hardship_loan_status
5
disbursement_method
1
debt_settlement_flag
2
debt_settlement_flag_date
30
settlement_status
4
settlement_date
35


In [16]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=5)


D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change 

array([0.98290342, 0.9819    , 0.98539854, 0.98239824, 0.98279656])

In [17]:
# Import and run PCA model 
from sklearn.decomposition import PCA
pca = PCA(n_components=10)
pca.fit(X)
X_pca = pca.transform(X)

In [18]:
# Test PCA on forest
rfc = ensemble.RandomForestClassifier()
cross_val_score(rfc, X_pca, Y, cv=10)

D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change 

array([0.82067173, 0.82986805, 0.82147141, 0.82686925, 0.83706517,
       0.8386    , 0.84713886, 0.84910947, 0.83470082, 0.8458767 ])

In [19]:
# Examine columns, look for ones related to payment amount or principal
X.columns[:40]

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'int_rate', 'installment', 'annual_inc', 'dti', 'delinq_2yrs',
       'inq_last_6mths', 'mths_since_last_delinq', 'mths_since_last_record',
       'open_acc', 'pub_rec', 'revol_bal', 'total_acc', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp',
       'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_amnt',
       'collections_12_mths_ex_med', 'mths_since_last_major_derog',
       'policy_code', 'annual_inc_joint', 'dti_joint', 'acc_now_delinq',
       'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m', 'open_act_il',
       'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il'],
      dtype='object')

In [20]:
X.columns[41:80]

Index(['il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
       'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_bc_dlq',
       'mths_since_recent_inq', 'mths_since_recent_revol_delinq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq'],
      dtype='object')

In [22]:
X.columns[81:120]

Index(['pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim',
       'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit',
       'revol_bal_joint', 'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths',
       'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util',
       'sec_app_open_act_il', 'sec_app_num_rev_accts',
       'sec_app_chargeoff_within_12_mths',
       'sec_app_collections_12_mths_ex_med',
       'sec_app_mths_since_last_major_derog', 'deferral_term',
       'hardship_amount', 'hardship_length', 'hardship_dpd',
       'orig_projected_additional_accrued_interest',
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'settlement_amount', 'settlement_percentage', 'settlement_term',
       'term_ 36 months', 'term_ 60 months', 'grade_A', 'grade_B', 'grade_C',
       'grade_D', 'grade_E', 'grade_F', 'grade_G', 'emp_length_0',
       'emp_length_1 year', 'emp_length_10+ years'],
      dtype='object')

In [23]:
X.columns[121:]

Index(['emp_length_3 years', 'emp_length_4 years', 'emp_length_5 years',
       'emp_length_6 years', 'emp_length_7 years', 'emp_length_8 years',
       'emp_length_9 years', 'emp_length_< 1 year', 'home_ownership_ANY',
       'home_ownership_MORTGAGE',
       ...
       'settlement_date_May-2018', 'settlement_date_Nov-2016',
       'settlement_date_Nov-2017', 'settlement_date_Nov-2018',
       'settlement_date_Oct-2016', 'settlement_date_Oct-2017',
       'settlement_date_Oct-2018', 'settlement_date_Sep-2016',
       'settlement_date_Sep-2017', 'settlement_date_Sep-2018'],
      dtype='object', length=304)

In [24]:
# Remove all columns related to payment amount and outstanding principal 
columns = ['out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv',
       'total_rec_prncp', 'total_rec_int','last_pymnt_amnt']

X_trim = X.drop(columns=columns)

# Rerun model with reduced data set
rfc = ensemble.RandomForestClassifier()
cross_val_score(rfc, X_trim, Y, cv=10)

D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change 

array([0.93862455, 0.93982407, 0.93882447, 0.93602559, 0.93662535,
       0.938     , 0.93377351, 0.9341605 , 0.9341605 , 0.93795036])