In [1]:
import numpy as np
x = np.array([0,1,2,3])
x


array([0, 1, 2, 3])

In [2]:
w = np.array([[0,1,2,3],[4,5,6,7]])
w


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [3]:
y = np.arange(8).reshape(2,4)
y

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
x = np.array([0,1,2,3])

#Square each value.
print(np.square(x))

#Square root of each value.
print(np.sqrt(x))

#Cosine of each value.
print(np.cos(x))


[0 1 4 9]
[0.         1.         1.41421356 1.73205081]
[ 1.          0.54030231 -0.41614684 -0.9899925 ]


In [5]:
x = np.array([0,1,2,3])

#Find the maximum value.
print(np.max(x))

#Find the minimum value.
print(np.min(x))

#Find the mean of the input array.
print(np.mean(x))

#Find the standard deviation of the input array
print(np.std(x))




3
0
1.5
1.118033988749895
